### ISSUE TITLE
Context_path environment variable for running behind a reverse proxy

### ISSUE THREAD

**Issue by samcro1967** [hoobs-org/HOOBS#1294]
**Is your feature request related to a problem? Please describe.**
Trying to run Hoobs behind a reverse proxy with SSO and MFA.  Unable to get Hoobs to work correctly on a subdirectory.

**Describe the solution you'd like**
A way to set a URL base/prefix/context_path so that Hobbs listens on http://192.168.1.150/hoobs instead of http://192.168.1.150.  Most of the containers I am running (40+) support this for running behind a reverse proxy.

**Describe alternatives you've considered**
I have tried setting this up using the reverse proxy to add and then strip the prefix, but the page does not load properly.

I am running Hoobs in a docker container.

**docker-compose.yml**
```
  hoobs:
    hostname: hoobs
    image: hoobs/hoobs
    container_name: hoobs
    volumes:
     - "${docker}/hoobs:/hoobs"
    environment:
     - TZ=America/Chicago
     - PUID=1000
     - PGID=1000
    network_mode: host
```
